"""Emit the LaTeX case-study composition table (case_study_composition.tex).

Counts are derived from the graph itself -- a node is a confounder if it is a
parent of both T and Y, a mediator if it lies on a T -> . -> Y path -- and then
cross-checked against the `feature_names` / `X.shape` actually stored in the
generated npz, so the table cannot drift from the data.

    python case_study/d_variation/make_roles_table.py [--check-root <shift dir>]
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))      # case_study/
sys.path.insert(0, _HERE)
from generation import CASE_STUDIES              # noqa: E402
from generation_d import build_dag_d, _n_hidden  # noqa: E402

DS = [5, 10, 20, 30, 40, 50]
PRETTY = {'Observed_Confounder': 'Observed Confounder',
          'Backdoor_Criterion': 'Backdoor Criterion',
          'Observed_Mediator': 'Observed Mediator',
          'Observed_Mediator_and_Confounder': 'Observed Mediator + Confounder',
          'Unobserved_Confounder': 'Unobserved Confounder',
          'Frontdoor_Criterion': 'Frontdoor Criterion'}
FORM = {'Observed_Confounder': (r'$d$', '--', '--', '--'),
        'Backdoor_Criterion': (r'$d$', '--', '--', r'$h$'),
        'Observed_Mediator': ('--', '--', r'$d$', '--'),
        'Observed_Mediator_and_Confounder':
            (r'$\lceil d/2\rceil$', '--', r'$\lfloor d/2\rfloor$', '--'),
        'Unobserved_Confounder': (r'$d$', r'$h$', '--', '--'),
        'Frontdoor_Criterion': (r'$d$', '--', '--', r'$h$')}


def roles(nodes):
    t = next(n.name for n in nodes if n.is_treatment)
    y = next(n.name for n in nodes if n.is_outcome)
    par = {n.name: set(n.parents) for n in nodes}
    r = dict(co=0, cu=0, mo=0, mu=0)
    for n in nodes:
        if n.name in (t, y):
            continue
        conf = (n.name in par[t]) and (n.name in par[y])
        med = (t in par[n.name]) and (n.name in par[y])
        if conf:
            r['co' if n.observed else 'cu'] += 1
        elif med:
            r['mo' if n.observed else 'mu'] += 1
    return r


def build(check_root=None):
    cell = lambda v: '--' if v == 0 else str(v)
    L = ['% Auto-generated by case_study/d_variation/make_roles_table.py',
         '% Counts verified against the generated npz feature_names.',
         r'\begin{table}[t]', r'  \centering', r'  \small',
         r'  \caption{Composition of the six case studies as the observed covariate'
         r' count $d$ varies. Hidden nodes scale as $h=\max(1,\lfloor d/10\rfloor)$'
         r' and are \emph{not} covariates, so $|X|=d$ in every cell. A node counts'
         r' as a confounder if it is a parent of both $T$ and $Y$, and as a mediator'
         r' if it lies on a $T\rightarrow\cdot\rightarrow Y$ path.}',
         r'  \label{tab:case-study-composition}',
         r'  \begin{tabular}{llcccc}', r'    \toprule',
         r'    & & \multicolumn{2}{c}{Confounders} & \multicolumn{2}{c}{Mediators} \\',
         r'    \cmidrule(lr){3-4}\cmidrule(lr){5-6}',
         r'    Case study & $d$ & Observed & Unobserved & Observed & Hidden \\',
         r'    \midrule']
    for ci, c in enumerate(CASE_STUDIES):
        f = FORM[c]
        L.append(rf'    \multirow{{{len(DS) + 1}}}{{*}}{{{PRETTY[c]}}}'
                 rf' & \textit{{any}} & {f[0]} & {f[1]} & {f[2]} & {f[3]} \\')
        L.append(r'    \cmidrule(l){2-6}')
        for d in DS:
            r = roles(build_dag_d(c, d))
            if check_root:
                hits = glob.glob(os.path.join(check_root, f'd{d}', c, 'N*',
                                              f'{c}_0.npz'))
                if not hits:
                    raise FileNotFoundError(f'no npz to check for {c} d={d}')
                z = np.load(hits[0], allow_pickle=True)
                names = list(map(str, z['feature_names']))
                expect = [n.name for n in build_dag_d(c, d) if n.observed]
                if names != expect or z['X'].shape[1] != d:
                    raise AssertionError(f'{c} d={d}: npz disagrees with builder')
            L.append(rf'     & {d} & {cell(r["co"])} & {cell(r["cu"])} '
                     rf'& {cell(r["mo"])} & {cell(r["mu"])} \\')
        L.append(r'    \midrule' if ci < len(CASE_STUDIES) - 1 else r'    \bottomrule')
    L += [r'  \end{tabular}', r'\end{table}']
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--check-root', default=os.path.join(_HERE, 'shift+2'),
                    help='shift root to cross-check counts against ("" to skip)')
    ap.add_argument('--out', default=os.path.join(_HERE, 'case_study_composition.tex'))
    a = ap.parse_args()
    tex = build(a.check_root or None)
    open(a.out, 'w').write(tex)
    print(f'wrote {a.out}'
          + (f' (cross-checked against {a.check_root})' if a.check_root else ''))
